#include "Monster.h"
#include <iostream>
#include <cstdlib>  // for rand() in Ghost evasion - generated by Copilot


// ============================================================================
// Base Monster class
// ============================================================================

// TODO: Implement Monster constructor
// HINTS:
// - MUST call Character base constructor
// - Initialize experience_reward and gold_reward
// - Loot table starts empty automatically
//
Monster::Monster(const std::string& name, int hp, int attack, int defense,
                 int exp_reward, int gold_reward)
    : Character(name, hp, attack, defense),
      experience_reward(exp_reward), gold_reward(gold_reward) {
}


// TODO: Implement Monster destructor
// HINTS:
// - Deallocate any allocated memory 
// - Loop through loot_table vector and delete each Item*
// - Clear the vector after deleting items
//
Monster::~Monster() {
    for (size_t i = 0; i < loot_table.size(); ++i) {
        delete loot_table[i];
    }
    loot_table.clear();
}


// TODO: Override displayStats
// HINTS:
// - Show monster name and HP
// - Format: "MonsterName [HP: current/max]"
// - Keep it simple - monsters don't need detailed stats display
//
void Monster::displayStats() const {
    // TODO: Display monster stats
    std::cout << getName() << " [HP: " << getCurrentHP() << "/" << getMaxHP() << "]" << std::endl;
}


// TODO: Implement addLoot
// HINTS:
// - Check if item pointer is not NULL
// - Add item to loot_table vector using push_back()
//
void Monster::addLoot(Item* item) {
    // TODO: Add item to loot table
    if (item != NULL) {
        loot_table.push_back(item);
    }
}


// TODO: Implement dropLoot
// HINTS:
// - Create a copy of the loot_table vector
// - Clear the original loot_table (transfer ownership to caller!)
// - Return the copy
// - This is important: caller now owns the items and must delete them
//
std::vector<Item*> Monster::dropLoot() {
    // TODO: Return loot and transfer ownership
    std::vector<Item*> dropped_loot = loot_table;
    loot_table.clear();
    return dropped_loot;
}



// TODO: Implement getAttackMessage (base version)
// HINTS:
// - Return default attack message
// - Format: "MonsterName attacks!"
// - Use getName() to get monster's name
//
std::string Monster::getAttackMessage() const {
    // TODO: Return attack message
    return getName() + " attacks!";
}


// ============================================================================
// Goblin - Weak but common enemy
// ============================================================================

// TODO: Implement Goblin constructor
// HINTS:
// - Call Monster constructor with these stats:
//   * Name: "Goblin"
//   * HP: 30
//   * Attack: 5
//   * Defense: 2
//   * Experience: 10
//   * Gold: 5
// - Add a small potion to loot table
// - Example: addLoot(new Consumable("Small Potion", "Restores 10 HP", 10));
//
Goblin::Goblin() 
    : Monster("Goblin", 30, 5, 2, 10, 5) {
    // TODO: Add loot items
    addLoot(new Consumable("Small Potion", "Restores 10 HP", 10));
}


// TODO: Override getAttackMessage for Goblin
// HINTS:
// - Return goblin-specific attack message
// - Example: "The goblin swipes at you with its rusty dagger!"
//
std::string Goblin::getAttackMessage() const {
    // TODO: Return goblin attack message
    return "The goblin swipes at you with its rusty dagger!";
}


// ============================================================================
// Skeleton - Undead warrior
// ============================================================================

// TODO: Implement Skeleton constructor
// HINTS:
// - Call Monster constructor with these stats:
//   * Name: "Skeleton"
//   * HP: 40
//   * Attack: 8
//   * Defense: 4
//   * Experience: 20
//   * Gold: 10
// - Add an old sword to loot table
//
Skeleton::Skeleton()
    : Monster("Skeleton", 40, 8, 4, 20, 10) {
    // TODO: Add loot items
    addLoot(new Weapon("Old Sword", "A rusty old sword", 5));
}


// TODO: Override getAttackMessage for Skeleton
// HINTS:
// - Return skeleton-specific attack message
// - Example: "The skeleton rattles its bones and slashes with a sword!"
//
std::string Skeleton::getAttackMessage() const {
    // TODO: Return skeleton attack message
    return "The skeleton rattles its bones and slashes with a sword!";
}

// ============================================================================
// Troll - A large brute: EXTRA CREDIT
// ============================================================================

Troll::Troll()
    : Monster("Troll", 120, 8, 5, 25, 15)  // High HP, low-ish attack
{
    addLoot(new Consumable("Troll Meat", "Kind of disgusting", 20));
    addLoot(new Armor("Troll Hide", "Thick hide that provides decent protection", 4));
}

std::string Troll::getAttackMessage() const {
    return "The troll smashes the ground, sending shockwaves toward you!";
}


// ============================================================================
// Ghost - Also an Undead Warrior (but ethereal): EXTRA CREDIT
// ============================================================================


Ghost::Ghost()
    : Monster("Ghost", 40, 12, 1, 20, 10)  // Low HP, moderate attack
{
    addLoot(new Consumable("Ectoplasm", "A strange glowing residue", 5));
}

std::string Ghost::getAttackMessage() const {
    return "The ghost lets out a chilling wail as it drifts through you!";
}

// Evasion implementation for Ghost
void Ghost::takeDamage(int dmg) {
    if (rand() % 2 == 0) {
        std::cout << "The ghost phases out — your attack passes through harmlessly!" << std::endl;
        return;
    }
    Monster::takeDamage(dmg);
}


// ============================================================================
// Wizard - Ranged magic attacker: EXTRA CREDIT
// ============================================================================

Wizard::Wizard()
    : Monster("Wizard", 50, 20, 3, 30, 25)  // High attack, low HP
{
    addLoot(new Consumable("Boosted Health Potion", "Restores 30 HP", 30));
    addLoot(new Weapon("Magic Staff", "A staff imbued with magical power", 20));
}

std::string Wizard::getAttackMessage() const {
    return "The wizard hurls a crackling bolt of energy at you!";
}


// ============================================================================
// Dragon - Boss enemy with special ability
// ============================================================================

// TODO: Implement Dragon constructor
// HINTS:
// - Call Monster constructor with these stats:
//   * Name: "Dragon"
//   * HP: 150
//   * Attack: 20
//   * Defense: 10
//   * Experience: 100
//   * Gold: 50
// - Add legendary loot:
//   * Dragon Slayer sword (damage +10)
//   * Dragon Scale Armor (defense +8)
//   * Greater Health Potion (heals 100 HP)
//
Dragon::Dragon()
    : Monster("Dragon", 150, 20, 10, 100, 50) {
    // TODO: Add legendary loot items
    addLoot(new Weapon("Dragon Slayer Sword", "A legendary sword that slays dragons", 10));
    addLoot(new Armor("Dragon Scale Armor", "Armor made from dragon scales", 8));
    addLoot(new Consumable("Greater Health Potion", "Restores 100 HP", 100));
}


// TODO: Override getAttackMessage for Dragon
// HINTS:
// - Return dragon-specific attack message
// - Example: "The dragon breathes fire at you!"
//
std::string Dragon::getAttackMessage() const {
    // TODO: Return dragon attack message
    return "The dragon breathes fire at you!";
}


// TODO: Override calculateDamage for Dragon
// HINTS:
// - Call Monster::calculateDamage() to get base damage
// - Add bonus fire damage (+5)
// - Return total damage
// - This makes the dragon hit harder than other monsters!
//
int Dragon::calculateDamage() const {
    // TODO: Calculate damage with fire bonus
    int base_damage = Monster::calculateDamage();
    return base_damage + 5;
}
